<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25520" started-at="2020-02-21T01:28:23Z" finished-at="2020-02-21T01:28:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25520" started-at="2020-02-21T01:28:23Z" finished-at="2020-02-21T01:28:49Z">
      <class name="com.yourLogo.testCases.checkEmailRegistration">
        <test-method status="PASS" signature="TC_ApplicationLaunch()[pri:0, instance:com.yourLogo.testCases.checkEmailRegistration@1a677343]" name="TC_ApplicationLaunch" is-config="true" duration-ms="12244" started-at="2020-02-21T01:28:23Z" finished-at="2020-02-21T01:28:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_ApplicationLaunch -->
        <test-method status="FAIL" signature="TC_emailCheck()[pri:0, instance:com.yourLogo.testCases.checkEmailRegistration@1a677343]" name="TC_emailCheck" duration-ms="13131" started-at="2020-02-21T01:28:36Z" finished-at="2020-02-21T01:28:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User account creation page is loaded instead of the error message.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User account creation page is loaded instead of the error message.
at org.testng.Assert.fail(Assert.java:96)
at pageObjects.HomePage.siginEmailCheck(HomePage.java:48)
at com.yourLogo.testCases.checkEmailRegistration.TC_emailCheck(checkEmailRegistration.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_emailCheck -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.yourLogo.testCases.checkEmailRegistration@1a677343]" name="tearDown" is-config="true" duration-ms="108" started-at="2020-02-21T01:28:49Z" finished-at="2020-02-21T01:28:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.yourLogo.testCases.checkEmailRegistration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
